// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "todo", input: never, result: null } | 
        { key: "todo2", input: never, result: null } | 
        { key: "todo3", input: never, result: null },
    mutations: never,
    subscriptions: 
        { key: "demoSubscriptions", input: never, result: string }
};
