// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "demo", input: [[number, [null, null, null]], [null, null]], result: null },
    mutations: never,
    subscriptions: never
};
