// DO NOT MODIFY. This file was generated by Specta and is used to keep rspc internally type safe.
// Checkout the unit test 'export_internal_types' to see where this files comes from!

/**
 * Represents a Typescript procedure file which is generated by the Rust code.
 * This is codegenerated Typescript file is how we can validate the types on the frontend match Rust.
 * 
 * @internal
 */
export type ProcedureDef = { key: string; input: any; result: any }