// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.
export type Procedures = {
  queries:
    | { key: "X-Demo-Header"; input: never; result: string; error: Error }
    | { key: "echo"; input: string; result: string; error: Error }
    | { key: "error"; input: never; result: string; error: Error }
    | { key: "transformMe"; input: never; result: string; error: Error }
    | { key: "version"; input: never; result: string; error: Error };
  mutations:
    | { key: "error"; input: never; result: string; error: Error }
    | { key: "sendMsg"; input: string; result: string; error: Error };
  subscriptions: { key: "pings"; input: never; result: string; error: Error };
};

export type Error = string;
