// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export interface Operations { queries: Queries, mutations: Mutations, subscriptions: Subscriptions }

export type Queries = | { key: "getUser"; arg: number; result: number; } | { key: "version"; arg: null; result: string; };

export type Mutations = | { key: "sayHi"; arg: string; result: null; };

export type Subscriptions = | { key: "pings"; arg: null; result: string; };
