// My custom header
// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type ProceduresLegacy = { queries: { key: "echo"; input: string; result: string } | { key: "error"; input: null; result: string } | { key: "nested.hello"; input: null; result: string } | { key: "transformMe"; input: null; result: string } | { key: "version"; input: null; result: string }; mutations: { key: "sendMsg"; input: string; result: string }; subscriptions: { key: "pings"; input: null; result: string } }

export { Procedures } from './bindings_t';