// My custom header
// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
	echo: { input: string, output: string, error: unknown },
	error: { input: null, output: string, error: unknown },
	nested: {
	hello: { input: null, output: string, error: unknown },
},
	pings: { input: null, output: string, error: unknown },
	sendMsg: { input: string, output: string, error: unknown },
	transformMe: { input: null, output: string, error: unknown },
	version: { input: null, output: string, error: unknown },
}
//# sourceMappingURL=bindings_t.d.ts.map