// My custom header
// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
	: {},
	: {},
	: {},
	: {},
	: {},
	: {},
	: {},
}
