// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.
export type Procedures = {
  queries:
    | { key: "X-Demo-Header"; input: never; result: string }
    | { key: "echo"; input: string; result: string }
    | { key: "error"; input: never; result: string }
    | { key: "serveFile"; input: never; result: null }
    | { key: "transformMe"; input: never; result: string }
    | { key: "version"; input: never; result: string };
  mutations:
    | { key: "error"; input: never; result: string }
    | { key: "sendMsg"; input: string; result: string };
  subscriptions:
    | {
        key: "errorPings";
        input: never;
        result: string | { code: ErrorCode; message: string };
      }
    | { key: "pings"; input: never; result: string }
    | { key: "testSubscriptionShutdown"; input: never; result: number };
};

/**
 * TODO
 */
export type ErrorCode =
  | "BadRequest"
  | "Unauthorized"
  | "Forbidden"
  | "NotFound"
  | "Timeout"
  | "Conflict"
  | "PreconditionFailed"
  | "PayloadTooLarge"
  | "MethodNotSupported"
  | "ClientClosedRequest"
  | "InternalServerError";
