// This file is generated by the Axum example at `./examples/axum.
mod bindings;

#[tokio::main]
async fn main() {
    let client = rspc_client::Client::new("http://[::]:4000/rspc");

    println!("{:?}", client.exec::<bindings::version>(()).await);
    println!(
        "{:?}",
        client
            .exec::<bindings::echo>("Some random string!".into())
            .await
    );
    println!(
        "{:?}",
        client
            .exec::<bindings::sendMsg>("Hello from rspc Rust client!".into())
            .await
    );

    // TODO: Subscription example.
}
