use crate::ts::ts_export_datatype;
use crate::*;
use lazy_static::lazy_static;
use std::collections::BTreeMap;
use std::sync::Mutex;

lazy_static! {
    /// Global type store for collecting custom types to export.
    ///
    /// Populated by `#[ctor]` functions defined in the [`Type`](derive@crate::Type) macro.
    pub static ref TYPES: Mutex<BTreeMap<&'static str, DataType>> = Mutex::new(Default::default());
}

/// Exports all types in the [`TYPES`](static@crate::export::TYPES) map to the provided TypeScript file.
pub fn export_types_ts(path: &str) {
    let mut out = "// This file has been generated by Specta. DO NOT EDIT.\n\n".to_string();

    for (_, typ) in &*TYPES.lock().unwrap() {
        out += &ts_export_datatype(&typ).unwrap();
        out += "\n\n";
    }

    std::fs::write(path, out).ok();
}
