use crate::*;
use once_cell::sync::Lazy;
use std::collections::BTreeMap;
use std::sync::Mutex;

/// Global type store for collecting custom types to export.
///
/// Populated by `#[ctor]` functions defined in the [`Type`](derive@crate::Type) macro.
pub static TYPES: Lazy<Mutex<BTreeMap<&'static str, DataType>>> = Lazy::new(Default::default);

/// Exports all types in the [`TYPES`](static@crate::export::TYPES) map to the provided TypeScript file.
#[allow(clippy::panic)]
pub fn ts(path: &str) {
    let mut out = "// This file has been generated by Specta. DO NOT EDIT.\n\n".to_string();

    for (name, typ) in &*TYPES.lock().expect("Failed to acquire lock on 'TYPES'") {
        out += &ts::export_datatype(typ)
            .unwrap_or_else(|_| panic!("Type '{name}' cannot be exported"));
        out += "\n\n";
    }

    std::fs::write(path, out).ok();
}
